config/routes.rb
Rails.application.routes.draw do
  resources :personagems
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personagem.rb
class Personagem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/personagems_controller.rb
class PersonagemsController < ApplicationController
  before_action :set_personagem, only: %i[ show edit update destroy ]

  # GET /personagems or /personagems.json
  def index
    @personagems = Personagem.all
  end

  # GET /personagems/1 or /personagems/1.json
  def show
  end

  # GET /personagems/new
  def new
    @personagem = Personagem.new
  end

  # GET /personagems/1/edit
  def edit
  end

  # POST /personagems or /personagems.json
  def create
    @personagem = Personagem.new(personagem_params)

    respond_to do |format|
      if @personagem.save
        format.html { redirect_to personagem_url(@personagem), notice: "Personagem was successfully created." }
        format.json { render :show, status: :created, location: @personagem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personagems/1 or /personagems/1.json
  def update
    respond_to do |format|
      if @personagem.update(personagem_params)
        format.html { redirect_to personagem_url(@personagem), notice: "Personagem was successfully updated." }
        format.json { render :show, status: :ok, location: @personagem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personagems/1 or /personagems/1.json
  def destroy
    @personagem.destroy

    respond_to do |format|
      format.html { redirect_to personagems_url, notice: "Personagem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personagem
      @personagem = Personagem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def personagem_params
      params.require(:personagem).permit(:nome, :descricao, :imagem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personagems_helper.rb
module PersonagemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUDPersonagens2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personagems/_form.html.erb
<%= form_with(model: personagem) do |form| %>
  <% if personagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personagem.errors.count, "error") %> prohibited this personagem from being saved:</h2>

      <ul>
        <% personagem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/personagems/edit.html.erb
<h1>Editing Personagem</h1>

<%= render 'form', personagem: @personagem %>

<%= link_to 'Show', @personagem %> |
<%= link_to 'Back', personagems_path %>

app/views/personagems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personagems</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personagems.each do |personagem| %>
      <tr>
        <td><%= personagem.nome %></td>
        <td><%= personagem.descricao %></td>
        <td><%= personagem.imagem %></td>
        <td><%= link_to 'Show', personagem %></td>
        <td><%= link_to 'Edit', edit_personagem_path(personagem) %></td>
        <td><%= link_to 'Destroy', personagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personagem', new_personagem_path %>

app/views/personagems/new.html.erb
<h1>New Personagem</h1>

<%= render 'form', personagem: @personagem %>

<%= link_to 'Back', personagems_path %>

app/views/personagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @personagem.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @personagem.descricao %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @personagem.imagem %>
</p>

<%= link_to 'Edit', edit_personagem_path(@personagem) %> |
<%= link_to 'Back', personagems_path %>